on:
  push:
    paths:
      - "**.vue"
      - "**.html"
      - "**.ts"
      - "**.js"
      - "**.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: "./dist"
          name: frontend
