on:
  push:
    paths:
      - "**.vue"
      - "**.html"
      - "**.ts"
      - "**.js"
      - "**.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: |
          npm i
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: "./dist"
          name: pages
